### ISSUE TITLE
Cannot read properties of undefined (reading 'createPromiseCapability')

### ISSUE THREAD

**Issue by weichow23** [m-damien/Charagraph#1]
I found the following two problems in your code:
1. I recommend using `npm install` instead of `npm install .` , otherwise some dependencies are missing (react-scripts typescript react etc).

2. `npm start` runs your program after using `npm install` as you instructed, but it gives you the following error
![Snipaste_2023-12-15_18-36-57](https://github.com/m-damien/Charagraph/assets/101793375/09be348a-c000-455a-a3ca-e28b175bdd46)
There seems to be something wrong with your code, but unfortunately I didn't find out how to fix it.
[reference](https://stackoverflow.com/questions/67503850/cannot-read-property-createpromisecapability-of-undefined)

I'd appreciate it if you could consider my suggestion or provide me with more detailed instructions on how to enable your code and solve the problem2.

**Comment by m-damien** [comment]
Hi @zjuerme ,

Thanks for reporting the issue. Seems like resources and libraries could not be loaded. I added the PUBLIC_URL to all the paths. Can you try again now?

**Comment by weichow23** [comment]
Thank you, it now run successfully😊
